### ISSUE TITLE
./pomo 245cloudでもターミナル上でカウントダウン始まって欲しい

### ISSUE THREAD

**Issue by pandeiro245** [tektoh/pomo#2]
# 現在はこう
- `./pomo play` でターミナル上のカウントダウン開始
- `./pomo 245cloud` で245cloud起動
# これが理想
- `./pomo 245cloud` すると245cloud起動かつplayのようにターミナル上のカウントダウン開始

**Comment by segawa-sh** [comment]
なるほどすばらしい∑(ﾟДﾟ)

**Comment by pandeiro245** [comment]
何卒！

**Comment by pandeiro245** [comment]
@tektoh いい感じに動きました！ありがとうございます！！
